// <auto-generated />
namespace PBL3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class edittringlength4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edittringlength4));
        
        string IMigrationMetadata.Id
        {
            get { return "202206030321184_edittringlength4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
